title: "Denuncias Arquitectura España"
description: "Plataforma anónima para denunciar malas condiciones laborales en despachos de arquitectura"
url: "https://tu-usuario.github.io"
baseurl: "/planta-baixa"

# GitHub Pages configuration
theme: null
plugins: []

# SEO
lang: es
author: "Denuncias Arquitectura España"

# Exclude files from Jekyll processing
exclude:
  - README.md
  - package.json
  - node_modules/
  - .gitignore 